# Generated by Django 4.2.3 on 2023-07-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='answer',
            name='main_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='answer',
            name='recommand_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='answer',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
