# Generated by Django 4.2.3 on 2023-07-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_chathistory_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='like',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
