# Generated by Django 4.2.3 on 2023-07-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chat_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='thumbnail',
        ),
    ]
