# Generated by Django 4.2.3 on 2023-07-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_chat_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ChatHistory',
            new_name='chat',
        ),
    ]
