# Generated by Django 4.2.3 on 2023-07-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_question_answer_alter_comment_chat_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='like',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
